import Recipes from '@/components/recipes/Recipes';
import UsersPage from '@/components/UsersPage/UsersPage';
import { UsersIcon } from 'lucide-react';
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "Home page",
  description: "Generated by create next app",
};
const Home = async () => {
  const data = await fetch("https://dummyjson.com/users")
  const users = await data.json()
  console.log(users);
  
    return (
    <div>
      <UsersPage data={users}/>
    </div>
  )
}

export default React.memo(Home)