import { Metadata } from 'next';
import React from 'react'
export const metadata: Metadata = {
  title: "Users page",
  description: "Generated by create next app",
};
const Users = () => {
  return (
    <div>Users</div>
  )
}

export default React.memo(Users)