import { Metadata } from 'next';
import React from 'react'
import RecipesCart from '@/components/recipes/Recipes';

export const metadata: Metadata = {
  title: "Recipes page",
  description: "Generated by create next app",
};
const Recipes = async () => {
  const data = await fetch("https://dummyjson.com/recipes")
  const recipes = await data.json()
  return (
    <div>
      <RecipesCart data={recipes} />
    </div>
  )
}

export default React.memo(Recipes)