import PostsPage from '@/components/Posts/PostsPage';
import { Metadata } from 'next';
import React from 'react'
export const metadata: Metadata = {
  title: "Posts page",
  description: "Generated by create next app",
};
const Posts = async () => {
  const data = await fetch("https://dummyjson.com/posts")
  const posts = await data.json()
  console.log(posts);
  
    return (
    <div>
      <PostsPage data={posts}/>
    </div>
  )
}

export default Posts