import CartsPage from '@/components/Cart/CartsPage';
import { Metadata } from 'next';
import React from 'react'
export const metadata: Metadata = {
  title: "Carts page",
  description: "Generated by create next app",
};
const Carts = async () => {
  const data = await fetch("https://dummyjson.com/carts")
  const carts = await data.json()
  console.log(carts);
  return (
    <div>
      <CartsPage data={carts}/>
    </div>
  )
}

export default Carts