import { Metadata } from 'next';
import React from 'react'
import ProductsPage from '@/components/Products/Products'
export const metadata: Metadata = {
  title: "Products page",
  description: "Generated by create next app",
};
const Products = async () => {
  const data = await fetch("https://dummyjson.com/products")
  const products = await data.json() 
  console.log(products);
  
  return (
    <div>
      <ProductsPage data={products}/>
    </div>
  )
}

export default React.memo(Products)